# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(554, 711)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icons/AVA-mainWindow.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("QWidget {\n"
"background-color: qlineargradient(spread:pad, x1:0.517, y1:1, x2:0.493, y2:0, stop:0 rgba(49, 49, 49, 207), stop:1 rgba(72, 72, 72, 255));}\n"
"\n"
";QMainWindow, QStatusBar, QMenuBar {\n"
"border-radius:10px;}\n"
"\n"
"\n"
"")
        MainWindow.setIconSize(QtCore.QSize(40, 40))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("")
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout_6 = QtWidgets.QGridLayout()
        self.gridLayout_6.setContentsMargins(10, 5, 10, 0)
        self.gridLayout_6.setSpacing(0)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.frame1 = QtWidgets.QFrame(self.centralwidget)
        self.frame1.setStyleSheet("QFrame {\n"
"border-radius:10%;\n"
"border: 2px solid rgb(100, 100, 100);\n"
"padding: 2px;\n"
"}")
        self.frame1.setObjectName("frame1")
        self.gridLayout_1 = QtWidgets.QGridLayout(self.frame1)
        self.gridLayout_1.setContentsMargins(5, 10, 5, 5)
        self.gridLayout_1.setSpacing(0)
        self.gridLayout_1.setObjectName("gridLayout_1")
        self.gridLayout_label = QtWidgets.QGridLayout()
        self.gridLayout_label.setContentsMargins(0, -1, -1, -1)
        self.gridLayout_label.setObjectName("gridLayout_label")
        self.label = QtWidgets.QLabel(self.frame1)
        self.label.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMaximumSize(QtCore.QSize(190, 185))
        self.label.setStyleSheet("background-color: 0 ;\n"
"border: 2px solid rgb(100, 100, 100);\n"
"border-radius: 5%;\n"
"padding: 10px;")
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("icons/AVA.png"))
        self.label.setScaledContents(True)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout_label.addWidget(self.label, 0, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.gridLayout_1.addLayout(self.gridLayout_label, 0, 0, 3, 2)
        self.gridLayout_7 = QtWidgets.QGridLayout()
        self.gridLayout_7.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.gridLayout_7.setContentsMargins(-1, 0, 0, 0)
        self.gridLayout_7.setSpacing(0)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.label_Volume = QtWidgets.QLabel(self.frame1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_Volume.sizePolicy().hasHeightForWidth())
        self.label_Volume.setSizePolicy(sizePolicy)
        self.label_Volume.setMinimumSize(QtCore.QSize(180, 0))
        self.label_Volume.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_Volume.setFont(font)
        self.label_Volume.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_Volume.setStyleSheet("color: rgb(180, 180, 180); \n"
"")
        self.label_Volume.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Volume.setObjectName("label_Volume")
        self.gridLayout_7.addWidget(self.label_Volume, 1, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.slider_Volume = QtWidgets.QSlider(self.frame1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.slider_Volume.sizePolicy().hasHeightForWidth())
        self.slider_Volume.setSizePolicy(sizePolicy)
        self.slider_Volume.setMinimumSize(QtCore.QSize(180, 0))
        self.slider_Volume.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.slider_Volume.setStyleSheet("QSlider {\n"
"    background-color: 0;\n"
"}\n"
"\n"
"QSlider::groove:horizontal {\n"
"    border: 0px solid #999999;\n"
"    height: 10px;\n"
"    margin: 1px 0;\n"
"}\n"
"\n"
"QSlider::handle:horizontal {\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:1, stop:0 #b4b4b4, stop:1 #8f8f8f);\n"
"    border: 1px solid #5c5c5c;\n"
"    width: 10px;\n"
"    margin: -3px 0;\n"
"    border-radius: 3px;\n"
"}\n"
"\n"
"QSlider::add-page:qlineargradient {\n"
"    background: white;\n"
"    border-top-right-radius: 5px;\n"
"    border-bottom-right-radius: 5px;\n"
"    border-top-left-radius: 0px;\n"
"    border-bottom-left-radius: 0px;\n"
"}\n"
"\n"
"QSlider::sub-page:qlineargradient {\n"
"    background: qradialgradient(spread:pad, cx:0.505, cy:0.522818, radius:1.044, fx:0.5, fy:0.523, stop:0.273632 rgba(255, 128, 0, 255), stop:1 rgba(102, 68, 0, 255));\n"
"    border-top-right-radius: 0px;\n"
"    border-bottom-right-radius: 0px;\n"
"    border-top-left-radius: 5px;\n"
"    border-bottom-left-radius: 5px;\n"
"}\n"
"\n"
"\n"
"\n"
"QToolTip {\n"
"    font: \"MS Shell Dlg 2\"; \n"
"    color: rgb(180, 180, 180); \n"
"    background-color: qlineargradient(spread:pad, x1:0.517, y1:1, x2:0.493, y2:0, stop:0 rgba(49, 49, 49, 207), stop:1 rgba(72, 72, 72, 255)); \n"
"    border: 0px; }\n"
"")
        self.slider_Volume.setMaximum(100)
        self.slider_Volume.setSingleStep(5)
        self.slider_Volume.setPageStep(5)
        self.slider_Volume.setProperty("value", 20)
        self.slider_Volume.setOrientation(QtCore.Qt.Horizontal)
        self.slider_Volume.setObjectName("slider_Volume")
        self.gridLayout_7.addWidget(self.slider_Volume, 0, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.gridLayout_1.addLayout(self.gridLayout_7, 3, 2, 1, 2)
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setContentsMargins(-1, 0, -1, -1)
        self.gridLayout_4.setSpacing(0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.frame_but = QtWidgets.QFrame(self.frame1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_but.sizePolicy().hasHeightForWidth())
        self.frame_but.setSizePolicy(sizePolicy)
        self.frame_but.setMaximumSize(QtCore.QSize(16777215, 50))
        self.frame_but.setStyleSheet("QFrame {\n"
"border: 1px solid rgb(100, 100, 100);\n"
"}")
        self.frame_but.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_but.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_but.setObjectName("frame_but")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_but)
        self.horizontalLayout.setContentsMargins(2, 2, 2, 2)
        self.horizontalLayout.setSpacing(2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(2, 20, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.pushButton_Play = QtWidgets.QPushButton(self.frame_but)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_Play.sizePolicy().hasHeightForWidth())
        self.pushButton_Play.setSizePolicy(sizePolicy)
        self.pushButton_Play.setMinimumSize(QtCore.QSize(36, 36))
        self.pushButton_Play.setMaximumSize(QtCore.QSize(36, 36))
        self.pushButton_Play.setStyleSheet("QPushButton {\n"
"    border-width: 1px;\n"
"    border-style:solid;\n"
"    border-color: rgb(255, 255, 255);\n"
"    border-radius:18%;\n"
"\n"
"    background-color: qradialgradient(spread:pad, cx:0.505, cy:0.522818, radius:1.044, fx:0.5, fy:0.523, stop:0.134328 rgba(255, 128, 0, 255), stop:0.751244 rgba(102, 68, 0, 255));\n"
"}\n"
"QPushButton:hover {\n"
"    background-color:qradialgradient(spread:pad, cx:0.505, cy:0.522818, radius:1.044, fx:0.5, fy:0.523, stop:0.233831 rgba(255, 128, 0, 255), stop:0.751244 rgba(102, 68, 0, 255));\n"
"    background-color: qradialgradient(spread:pad, cx:0.505, cy:0.522818, radius:1.044, fx:0.5, fy:0.523, stop:0.228856 rgba(255, 145, 34, 255), stop:0.751244 rgba(102, 68, 0, 255));\n"
"}\n"
"QPushButton:pressed {\n"
"    border-color:  rgb(100, 100, 100);\n"
"    background-color:qradialgradient(spread:pad, cx:0.505, cy:0.522818, radius:1.044, fx:0.5, fy:0.523, stop:0 rgba(255, 128, 0, 255), stop:0.577114 rgba(102, 68, 0, 255));\n"
"}\n"
"\n"
"QToolTip { color: rgb(180, 180, 180); \n"
"    background-color: qlineargradient(spread:pad, x1:0.517, y1:1, x2:0.493, y2:0, stop:0 rgba(49, 49, 49, 207), stop:1 rgba(72, 72, 72, 255)); \n"
"    border: 0px; }")
        self.pushButton_Play.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("icons/play.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_Play.setIcon(icon1)
        self.pushButton_Play.setIconSize(QtCore.QSize(25, 25))
        self.pushButton_Play.setObjectName("pushButton_Play")
        self.horizontalLayout.addWidget(self.pushButton_Play)
        spacerItem1 = QtWidgets.QSpacerItem(5, 20, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.pushButton_Pause = QtWidgets.QPushButton(self.frame_but)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_Pause.sizePolicy().hasHeightForWidth())
        self.pushButton_Pause.setSizePolicy(sizePolicy)
        self.pushButton_Pause.setMinimumSize(QtCore.QSize(36, 36))
        self.pushButton_Pause.setMaximumSize(QtCore.QSize(36, 36))
        self.pushButton_Pause.setStyleSheet("QPushButton {\n"
"    border-width: 1px;\n"
"    border-style:solid;\n"
"    border-color: rgb(255, 255, 255);\n"
"    border-radius:18%;\n"
"\n"
"    background-color: qradialgradient(spread:pad, cx:0.505, cy:0.522818, radius:1.044, fx:0.5, fy:0.523, stop:0.134328 rgba(255, 128, 0, 255), stop:0.751244 rgba(102, 68, 0, 255));\n"
"}\n"
"QPushButton:hover {\n"
"    background-color:qradialgradient(spread:pad, cx:0.505, cy:0.522818, radius:1.044, fx:0.5, fy:0.523, stop:0.233831 rgba(255, 128, 0, 255), stop:0.751244 rgba(102, 68, 0, 255));\n"
"    background-color: qradialgradient(spread:pad, cx:0.505, cy:0.522818, radius:1.044, fx:0.5, fy:0.523, stop:0.228856 rgba(255, 145, 34, 255), stop:0.751244 rgba(102, 68, 0, 255));\n"
"}\n"
"QPushButton:pressed {\n"
"    border-color:  rgb(100, 100, 100);\n"
"    background-color:qradialgradient(spread:pad, cx:0.505, cy:0.522818, radius:1.044, fx:0.5, fy:0.523, stop:0 rgba(255, 128, 0, 255), stop:0.577114 rgba(102, 68, 0, 255));\n"
"}\n"
"\n"
"QToolTip { color: rgb(180, 180, 180); \n"
"    background-color: qlineargradient(spread:pad, x1:0.517, y1:1, x2:0.493, y2:0, stop:0 rgba(49, 49, 49, 207), stop:1 rgba(72, 72, 72, 255)); \n"
"    border: 0px; }")
        self.pushButton_Pause.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("icons/pause.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_Pause.setIcon(icon2)
        self.pushButton_Pause.setIconSize(QtCore.QSize(30, 30))
        self.pushButton_Pause.setObjectName("pushButton_Pause")
        self.horizontalLayout.addWidget(self.pushButton_Pause)
        spacerItem2 = QtWidgets.QSpacerItem(5, 20, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.pushButton_Stop = QtWidgets.QPushButton(self.frame_but)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_Stop.sizePolicy().hasHeightForWidth())
        self.pushButton_Stop.setSizePolicy(sizePolicy)
        self.pushButton_Stop.setMinimumSize(QtCore.QSize(36, 36))
        self.pushButton_Stop.setMaximumSize(QtCore.QSize(36, 36))
        self.pushButton_Stop.setStyleSheet("QPushButton {\n"
"    border-width: 1px;\n"
"    border-style:solid;\n"
"    border-color: rgb(255, 255, 255);\n"
"    border-radius:18%;\n"
"\n"
"    background-color: qradialgradient(spread:pad, cx:0.505, cy:0.522818, radius:1.044, fx:0.5, fy:0.523, stop:0.134328 rgba(255, 128, 0, 255), stop:0.751244 rgba(102, 68, 0, 255));\n"
"}\n"
"QPushButton:hover {\n"
"    background-color:qradialgradient(spread:pad, cx:0.505, cy:0.522818, radius:1.044, fx:0.5, fy:0.523, stop:0.233831 rgba(255, 128, 0, 255), stop:0.751244 rgba(102, 68, 0, 255));\n"
"    background-color: qradialgradient(spread:pad, cx:0.505, cy:0.522818, radius:1.044, fx:0.5, fy:0.523, stop:0.228856 rgba(255, 145, 34, 255), stop:0.751244 rgba(102, 68, 0, 255));\n"
"}\n"
"QPushButton:pressed {\n"
"    border-color:  rgb(100, 100, 100);\n"
"    background-color:qradialgradient(spread:pad, cx:0.505, cy:0.522818, radius:1.044, fx:0.5, fy:0.523, stop:0 rgba(255, 128, 0, 255), stop:0.577114 rgba(102, 68, 0, 255));\n"
"}\n"
"\n"
"QToolTip { color: rgb(180, 180, 180); \n"
"    background-color: qlineargradient(spread:pad, x1:0.517, y1:1, x2:0.493, y2:0, stop:0 rgba(49, 49, 49, 207), stop:1 rgba(72, 72, 72, 255)); \n"
"    border: 0px; }\n"
"")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("icons/stop.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_Stop.setIcon(icon3)
        self.pushButton_Stop.setIconSize(QtCore.QSize(25, 25))
        self.pushButton_Stop.setObjectName("pushButton_Stop")
        self.horizontalLayout.addWidget(self.pushButton_Stop)
        spacerItem3 = QtWidgets.QSpacerItem(5, 20, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem3)
        self.pushButton_Previous_track = QtWidgets.QPushButton(self.frame_but)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_Previous_track.sizePolicy().hasHeightForWidth())
        self.pushButton_Previous_track.setSizePolicy(sizePolicy)
        self.pushButton_Previous_track.setMinimumSize(QtCore.QSize(36, 36))
        self.pushButton_Previous_track.setMaximumSize(QtCore.QSize(36, 36))
        self.pushButton_Previous_track.setStyleSheet("QPushButton {\n"
"    border-width: 1px;\n"
"    border-style:solid;\n"
"    border-color: rgb(255, 255, 255);\n"
"    border-radius:18%;\n"
"\n"
"    background-color: qradialgradient(spread:pad, cx:0.505, cy:0.522818, radius:1.044, fx:0.5, fy:0.523, stop:0.134328 rgba(255, 128, 0, 255), stop:0.751244 rgba(102, 68, 0, 255));\n"
"}\n"
"QPushButton:hover {\n"
"    background-color:qradialgradient(spread:pad, cx:0.505, cy:0.522818, radius:1.044, fx:0.5, fy:0.523, stop:0.233831 rgba(255, 128, 0, 255), stop:0.751244 rgba(102, 68, 0, 255));\n"
"    background-color: qradialgradient(spread:pad, cx:0.505, cy:0.522818, radius:1.044, fx:0.5, fy:0.523, stop:0.228856 rgba(255, 145, 34, 255), stop:0.751244 rgba(102, 68, 0, 255));\n"
"}\n"
"QPushButton:pressed {\n"
"    border-color:  rgb(100, 100, 100);\n"
"    background-color:qradialgradient(spread:pad, cx:0.505, cy:0.522818, radius:1.044, fx:0.5, fy:0.523, stop:0 rgba(255, 128, 0, 255), stop:0.577114 rgba(102, 68, 0, 255));\n"
"}\n"
"\n"
"QToolTip { color: rgb(180, 180, 180); \n"
"    background-color: qlineargradient(spread:pad, x1:0.517, y1:1, x2:0.493, y2:0, stop:0 rgba(49, 49, 49, 207), stop:1 rgba(72, 72, 72, 255)); \n"
"    border: 0px; }")
        self.pushButton_Previous_track.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("icons/prev.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_Previous_track.setIcon(icon4)
        self.pushButton_Previous_track.setIconSize(QtCore.QSize(30, 30))
        self.pushButton_Previous_track.setObjectName("pushButton_Previous_track")
        self.horizontalLayout.addWidget(self.pushButton_Previous_track)
        spacerItem4 = QtWidgets.QSpacerItem(5, 20, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem4)
        self.pushButton_Next_track = QtWidgets.QPushButton(self.frame_but)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_Next_track.sizePolicy().hasHeightForWidth())
        self.pushButton_Next_track.setSizePolicy(sizePolicy)
        self.pushButton_Next_track.setMinimumSize(QtCore.QSize(36, 36))
        self.pushButton_Next_track.setMaximumSize(QtCore.QSize(36, 36))
        self.pushButton_Next_track.setStyleSheet("QPushButton {\n"
"    border-width: 1px;\n"
"    border-style:solid;\n"
"    border-color: rgb(255, 255, 255);\n"
"    border-radius:18%;\n"
"\n"
"    background-color: qradialgradient(spread:pad, cx:0.505, cy:0.522818, radius:1.044, fx:0.5, fy:0.523, stop:0.134328 rgba(255, 128, 0, 255), stop:0.751244 rgba(102, 68, 0, 255));\n"
"}\n"
"QPushButton:hover {\n"
"    background-color:qradialgradient(spread:pad, cx:0.505, cy:0.522818, radius:1.044, fx:0.5, fy:0.523, stop:0.233831 rgba(255, 128, 0, 255), stop:0.751244 rgba(102, 68, 0, 255));\n"
"    background-color: qradialgradient(spread:pad, cx:0.505, cy:0.522818, radius:1.044, fx:0.5, fy:0.523, stop:0.228856 rgba(255, 145, 34, 255), stop:0.751244 rgba(102, 68, 0, 255));\n"
"}\n"
"QPushButton:pressed {\n"
"    border-color:  rgb(100, 100, 100);\n"
"    background-color:qradialgradient(spread:pad, cx:0.505, cy:0.522818, radius:1.044, fx:0.5, fy:0.523, stop:0 rgba(255, 128, 0, 255), stop:0.577114 rgba(102, 68, 0, 255));\n"
"}\n"
"\n"
"QToolTip { color: rgb(180, 180, 180); \n"
"    background-color: qlineargradient(spread:pad, x1:0.517, y1:1, x2:0.493, y2:0, stop:0 rgba(49, 49, 49, 207), stop:1 rgba(72, 72, 72, 255)); \n"
"    border: 0px; }")
        self.pushButton_Next_track.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("icons/next.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_Next_track.setIcon(icon5)
        self.pushButton_Next_track.setIconSize(QtCore.QSize(30, 30))
        self.pushButton_Next_track.setObjectName("pushButton_Next_track")
        self.horizontalLayout.addWidget(self.pushButton_Next_track)
        spacerItem5 = QtWidgets.QSpacerItem(5, 20, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem5)
        self.pushButton_Open_file = QtWidgets.QPushButton(self.frame_but)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_Open_file.sizePolicy().hasHeightForWidth())
        self.pushButton_Open_file.setSizePolicy(sizePolicy)
        self.pushButton_Open_file.setMinimumSize(QtCore.QSize(36, 36))
        self.pushButton_Open_file.setMaximumSize(QtCore.QSize(36, 36))
        self.pushButton_Open_file.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.pushButton_Open_file.setStyleSheet("QPushButton {\n"
"    border-width: 1px;\n"
"    border-style:solid;\n"
"    border-color: rgb(255, 255, 255);\n"
"    border-radius:18%;\n"
"    background-color: qradialgradient(spread:pad, cx:0.505, cy:0.522818, radius:1.044, fx:0.5, fy:0.523, stop:0.134328 rgba(255, 128, 0, 255), stop:0.751244 rgba(102, 68, 0, 255));\n"
"}\n"
"QPushButton::menu-indicator { image: none; }\n"
"\n"
"QPushButton:hover {\n"
"    background-color:qradialgradient(spread:pad, cx:0.505, cy:0.522818, radius:1.044, fx:0.5, fy:0.523, stop:0.233831 rgba(255, 128, 0, 255), stop:0.751244 rgba(102, 68, 0, 255));\n"
"    background-color: qradialgradient(spread:pad, cx:0.505, cy:0.522818, radius:1.044, fx:0.5, fy:0.523, stop:0.228856 rgba(255, 145, 34, 255), stop:0.751244 rgba(102, 68, 0, 255));\n"
"}\n"
"QPushButton:pressed {\n"
"    border-color:  rgb(100, 100, 100);\n"
"    background-color:qradialgradient(spread:pad, cx:0.505, cy:0.522818, radius:1.044, fx:0.5, fy:0.523, stop:0 rgba(255, 128, 0, 255), stop:0.577114 rgba(102, 68, 0, 255));\n"
"}\n"
"\n"
"QToolTip { color: rgb(180, 180, 180); \n"
"    background-color: qlineargradient(spread:pad, x1:0.517, y1:1, x2:0.493, y2:0, stop:0 rgba(49, 49, 49, 207), stop:1 rgba(72, 72, 72, 255)); \n"
"    border: 0px; }")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("icons/files.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_Open_file.setIcon(icon6)
        self.pushButton_Open_file.setIconSize(QtCore.QSize(22, 22))
        self.pushButton_Open_file.setObjectName("pushButton_Open_file")
        self.horizontalLayout.addWidget(self.pushButton_Open_file)
        spacerItem6 = QtWidgets.QSpacerItem(5, 20, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem6)
        self.pushButton_Delete_file = QtWidgets.QPushButton(self.frame_but)
        self.pushButton_Delete_file.setMinimumSize(QtCore.QSize(36, 36))
        self.pushButton_Delete_file.setMaximumSize(QtCore.QSize(36, 36))
        self.pushButton_Delete_file.setStyleSheet("QPushButton {\n"
"    border-width: 1px;\n"
"    border-style:solid;\n"
"    border-color: rgb(255, 255, 255);\n"
"    border-radius:18%;\n"
"\n"
"    background-color: qradialgradient(spread:pad, cx:0.505, cy:0.522818, radius:1.044, fx:0.5, fy:0.523, stop:0.134328 rgba(255, 128, 0, 255), stop:0.751244 rgba(102, 68, 0, 255));\n"
"}\n"
"QPushButton:hover {\n"
"    background-color:qradialgradient(spread:pad, cx:0.505, cy:0.522818, radius:1.044, fx:0.5, fy:0.523, stop:0.233831 rgba(255, 128, 0, 255), stop:0.751244 rgba(102, 68, 0, 255));\n"
"    background-color: qradialgradient(spread:pad, cx:0.505, cy:0.522818, radius:1.044, fx:0.5, fy:0.523, stop:0.228856 rgba(255, 145, 34, 255), stop:0.751244 rgba(102, 68, 0, 255));\n"
"}\n"
"QPushButton:pressed {\n"
"    border-color:  rgb(100, 100, 100);\n"
"    background-color:qradialgradient(spread:pad, cx:0.505, cy:0.522818, radius:1.044, fx:0.5, fy:0.523, stop:0 rgba(255, 128, 0, 255), stop:0.577114 rgba(102, 68, 0, 255));\n"
"}\n"
"\n"
"QToolTip { color: rgb(180, 180, 180); \n"
"    background-color: qlineargradient(spread:pad, x1:0.517, y1:1, x2:0.493, y2:0, stop:0 rgba(49, 49, 49, 207), stop:1 rgba(72, 72, 72, 255)); \n"
"    border: 0px; }")
        self.pushButton_Delete_file.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("icons/delete.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_Delete_file.setIcon(icon7)
        self.pushButton_Delete_file.setIconSize(QtCore.QSize(30, 30))
        self.pushButton_Delete_file.setObjectName("pushButton_Delete_file")
        self.horizontalLayout.addWidget(self.pushButton_Delete_file)
        spacerItem7 = QtWidgets.QSpacerItem(2, 20, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem7)
        self.gridLayout_4.addWidget(self.frame_but, 1, 0, 1, 6)
        spacerItem8 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_4.addItem(spacerItem8, 0, 0, 1, 8)
        self.gridLayout_1.addLayout(self.gridLayout_4, 3, 0, 1, 2)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.gridLayout_3.setContentsMargins(0, -1, -1, -1)
        self.gridLayout_3.setSpacing(0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.frame = QtWidgets.QFrame(self.frame1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setMinimumSize(QtCore.QSize(200, 35))
        self.frame.setMaximumSize(QtCore.QSize(200, 35))
        self.frame.setStyleSheet("border: 2px solid rgb(100, 100, 100);\n"
"border-radius: 10%;\n"
"")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_Start = QtWidgets.QLabel(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_Start.sizePolicy().hasHeightForWidth())
        self.label_Start.setSizePolicy(sizePolicy)
        self.label_Start.setMinimumSize(QtCore.QSize(70, 25))
        self.label_Start.setMaximumSize(QtCore.QSize(100, 25))
        font = QtGui.QFont()
        font.setFamily("Terminal")
        font.setPointSize(12)
        self.label_Start.setFont(font)
        self.label_Start.setStyleSheet("background: none;\n"
"border:none;\n"
"color: rgb(180, 180, 180); \n"
"")
        self.label_Start.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Start.setObjectName("label_Start")
        self.horizontalLayout_2.addWidget(self.label_Start, 0, QtCore.Qt.AlignVCenter)
        self.line = QtWidgets.QFrame(self.frame)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout_2.addWidget(self.line)
        self.label_End = QtWidgets.QLabel(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_End.sizePolicy().hasHeightForWidth())
        self.label_End.setSizePolicy(sizePolicy)
        self.label_End.setMinimumSize(QtCore.QSize(70, 25))
        self.label_End.setMaximumSize(QtCore.QSize(100, 25))
        font = QtGui.QFont()
        font.setFamily("Terminal")
        font.setPointSize(12)
        self.label_End.setFont(font)
        self.label_End.setStyleSheet("background: none;\n"
"border:none;\n"
"color: rgb(180, 180, 180); \n"
"")
        self.label_End.setAlignment(QtCore.Qt.AlignCenter)
        self.label_End.setObjectName("label_End")
        self.horizontalLayout_2.addWidget(self.label_End, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.gridLayout_3.addWidget(self.frame, 0, 1, 1, 1, QtCore.Qt.AlignHCenter)
        self.gridLayout_1.addLayout(self.gridLayout_3, 0, 2, 1, 2)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setContentsMargins(0, 5, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.frame_2 = QtWidgets.QFrame(self.frame1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_2.sizePolicy().hasHeightForWidth())
        self.frame_2.setSizePolicy(sizePolicy)
        self.frame_2.setMinimumSize(QtCore.QSize(190, 140))
        self.frame_2.setMaximumSize(QtCore.QSize(190, 140))
        self.frame_2.setStyleSheet("padding:-5px;\n"
"background-color: rgb(0, 0, 0);")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.EqualizerWidget = MyEqualizer(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.EqualizerWidget.sizePolicy().hasHeightForWidth())
        self.EqualizerWidget.setSizePolicy(sizePolicy)
        self.EqualizerWidget.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.EqualizerWidget.setStyleSheet("border: 2px solid rgb(100, 100, 100);\n"
"border-radius: 5%;")
        self.EqualizerWidget.setObjectName("EqualizerWidget")
        self.verticalLayout_2.addWidget(self.EqualizerWidget)
        self.gridLayout.addWidget(self.frame_2, 0, 1, 1, 1)
        self.gridLayout_1.addLayout(self.gridLayout, 1, 2, 2, 2)
        self.gridLayout_6.addWidget(self.frame1, 0, 0, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_6)
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setContentsMargins(10, -1, 10, -1)
        self.gridLayout_5.setSpacing(0)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.slider_Duration = QtWidgets.QSlider(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.slider_Duration.sizePolicy().hasHeightForWidth())
        self.slider_Duration.setSizePolicy(sizePolicy)
        self.slider_Duration.setStyleSheet("QSlider {\n"
"    background-color: 0;\n"
"}\n"
"\n"
"QSlider::groove:horizontal {\n"
"    border: 0px solid #999999;\n"
"    height: 10px;\n"
"    margin: 1px 0;\n"
"}\n"
"\n"
"QSlider::handle:horizontal {\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:1, stop:0 #b4b4b4, stop:1 #8f8f8f);\n"
"    border: 1px solid #5c5c5c;\n"
"    width: 10px;\n"
"    margin: -2px 0;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QSlider::add-page:qlineargradient {\n"
"    background: white;\n"
"    border-top-right-radius: 5px;\n"
"    border-bottom-right-radius: 5px;\n"
"    border-top-left-radius: 0px;\n"
"    border-bottom-left-radius: 0px;\n"
"}\n"
"\n"
"QSlider::sub-page:qlineargradient {\n"
"    background: qradialgradient(spread:pad, cx:0.505, cy:0.522818, radius:1.044, fx:0.5, fy:0.523, stop:0.273632 rgba(255, 128, 0, 255), stop:1 rgba(102, 68, 0, 255));\n"
"    background-color: qradialgradient(spread:pad, cx:0.505, cy:0.522818, radius:1.044, fx:0.5, fy:0.523, stop:0.134328 rgba(255, 128, 0, 255), stop:0.751244 rgba(102, 68, 0, 255));\n"
"    border-top-right-radius: 0px;\n"
"    border-bottom-right-radius: 0px;\n"
"    border-top-left-radius: 5px;\n"
"    border-bottom-left-radius: 5px;\n"
"}\n"
"\n"
"")
        self.slider_Duration.setMaximum(100)
        self.slider_Duration.setSingleStep(10)
        self.slider_Duration.setPageStep(10)
        self.slider_Duration.setProperty("value", 0)
        self.slider_Duration.setOrientation(QtCore.Qt.Horizontal)
        self.slider_Duration.setObjectName("slider_Duration")
        self.gridLayout_5.addWidget(self.slider_Duration, 0, 0, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_5)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setContentsMargins(10, 0, 10, 5)
        self.gridLayout_2.setSpacing(0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.treeView_Playlist = MyTreeView(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.treeView_Playlist.sizePolicy().hasHeightForWidth())
        self.treeView_Playlist.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        self.treeView_Playlist.setFont(font)
        self.treeView_Playlist.setStyleSheet("QTreeView{border-radius:10%;\n"
"    border: 2px solid rgb(100, 100, 100);\n"
"    color: rgb(180, 180, 180); \n"
"}\n"
"QTreeView::item {\n"
"    padding: 3px;\n"
"}\n"
"\n"
"QTreeView::item:selected {\n"
"    border: 1px solid rgb(100, 100, 100);\n"
"    color: rgb(180, 180, 180); \n"
"    padding:2px;\n"
"}\n"
"\n"
"QTreeView::item:selected:active{\n"
"    background: rgb(100, 100, 100);\n"
"    padding:2px;\n"
"}\n"
"\n"
"QTreeView::item:selected:!active {\n"
"    background: rgb(100, 100, 100);\n"
"    padding:2px;\n"
"}\n"
"\n"
"QTreeView::item:closed:has-children:!has-siblings,\n"
"QTreeView::item:closed:has-children:has-siblings,\n"
"QTreeView::item:open:has-children:!has-siblings,\n"
"QTreeView::item:open:has-children:has-siblings  {\n"
"    border:2px solid qradialgradient(spread:pad, cx:0.505, cy:0.522818, radius:1.044, fx:0.5, fy:0.523, stop:0.273632 rgba(255, 128, 0, 255), stop:1 rgba(102, 68, 0, 255));\n"
"    border-top:none;\n"
"    border-left:none;\n"
"    border-right: none;\n"
"}\n"
"\n"
"QTreeView::branch:closed:has-children:!has-siblings,\n"
"QTreeView::branch:closed:has-children:has-siblings {\n"
"        border-image: none;\n"
"        image: url(icons/plus2.0.png);\n"
"}\n"
"\n"
"QTreeView::branch:open:has-children:!has-siblings,\n"
"QTreeView::branch:open:has-children:has-siblings  {\n"
"        border-image: none;\n"
"        image: url(icons/minus3.0.png);\n"
"}\n"
"\n"
"QScrollBar:vertical{\n"
"background-color: 0;\n"
"border-top-right-radius:10%;\n"
"border-bottom-right-radius:10%;\n"
"margin-left:10px;\n"
"}\n"
"QScrollBar::add-line:vertical, QScrollBar::sub-line:vertical{\n"
"      border: none;\n"
"      background: none;\n"
"}\n"
"QScrollBar::up-arrow:vertical, QScrollBar::down-arrow:vertical {\n"
"     background: none;\n"
"     color: none;\n"
" }\n"
"\n"
"QLineEdit{\n"
"border: 1px solid rgb(100, 100, 100);\n"
"color:  rgb(180, 180, 180);\n"
"padding-left: 1px;\n"
"padding-bottom: 1px;\n"
"}")
        self.treeView_Playlist.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.treeView_Playlist.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.treeView_Playlist.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.treeView_Playlist.setTabKeyNavigation(False)
        self.treeView_Playlist.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.treeView_Playlist.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectItems)
        self.treeView_Playlist.setSortingEnabled(True)
        self.treeView_Playlist.setHeaderHidden(True)
        self.treeView_Playlist.setObjectName("treeView_Playlist")
        self.gridLayout_2.addWidget(self.treeView_Playlist, 0, 0, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 554, 31))
        self.menubar.setStyleSheet("\n"
"QMenuBar::item {         \n"
"    margin: 1px;  \n"
"    color: rgb(180, 180, 180); \n"
"    padding: 2px 10px;\n"
"    border-radius: 5px;\n"
"    border:2px solid rgb(90, 90, 90);\n"
"}\n"
"\n"
"QMenuBar::item:selected {    \n"
"    background-color:rgb(65, 65, 65);\n"
"}\n"
"QMenuBar::item:pressed {\n"
"    background-color: rgb(75, 75, 75);\n"
"}\n"
"QMenu {\n"
"    color: rgb(180, 180, 180);\n"
"    background-color: qlineargradient(spread:pad, x1:0.517, y1:1, x2:0.493, y2:0, \n"
"    stop:0 rgba(49, 49, 49, 207), stop:1 rgba(72, 72, 72, 255)); \n"
"    border: 2px solid rgb(100, 100, 100);}\n"
"\n"
"QMenu::item:selected { \n"
"    background-color: rgb(80, 80, 80);}\n"
"\n"
"QMenu::separator {\n"
"    background: rgb(90, 90, 90);\n"
"    height : 1px;\n"
"}\n"
";QMenuBar {         \n"
"    background-color:transparent;\n"
"    background-color:rgb(65, 65, 65);\n"
"}")
        self.menubar.setObjectName("menubar")
        self.menuMain = QtWidgets.QMenu(self.menubar)
        self.menuMain.setStyleSheet("")
        self.menuMain.setObjectName("menuMain")
        self.menuAbout = QtWidgets.QMenu(self.menubar)
        self.menuAbout.setObjectName("menuAbout")
        MainWindow.setMenuBar(self.menubar)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        self.statusBar.setFont(font)
        self.statusBar.setStyleSheet("QStatusBar QLabel{\n"
"color:white;\n"
"font: 10pt \"MS Shell Dlg 2\";\n"
"margin-top: 1px;\n"
"margin-bottom: 3px;\n"
"qproperty-alignment: AlignCenter;\n"
"}\n"
"QStatusBar::item {\n"
"border-right: 2px solid rgb(100, 100, 100);\n"
"margin-right: -2px;\n"
"}")
        self.statusBar.setSizeGripEnabled(False)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)
        self.actionNew_Playllist = QtWidgets.QAction(MainWindow)
        self.actionNew_Playllist.setObjectName("actionNew_Playllist")
        self.actionFiles = QtWidgets.QAction(MainWindow)
        self.actionFiles.setObjectName("actionFiles")
        self.actionFolder = QtWidgets.QAction(MainWindow)
        self.actionFolder.setObjectName("actionFolder")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionHelp = QtWidgets.QAction(MainWindow)
        self.actionHelp.setObjectName("actionHelp")
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.menuMain.addAction(self.actionNew_Playllist)
        self.menuMain.addAction(self.actionFiles)
        self.menuMain.addAction(self.actionFolder)
        self.menuMain.addSeparator()
        self.menuMain.addAction(self.actionExit)
        self.menuAbout.addAction(self.actionHelp)
        self.menuAbout.addAction(self.actionAbout)
        self.menubar.addAction(self.menuMain.menuAction())
        self.menubar.addAction(self.menuAbout.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        self.label_Volume.setText(_translate("MainWindow", "Volume"))
        self.slider_Volume.setToolTip(_translate("MainWindow", "20%"))
        self.pushButton_Play.setToolTip(_translate("MainWindow", "Play"))
        self.pushButton_Pause.setToolTip(_translate("MainWindow", "Pause"))
        self.pushButton_Stop.setToolTip(_translate("MainWindow", "Stop"))
        self.pushButton_Previous_track.setToolTip(_translate("MainWindow", "Previous track"))
        self.pushButton_Next_track.setToolTip(_translate("MainWindow", "Next track"))
        self.pushButton_Open_file.setToolTip(_translate("MainWindow", "Add/Open ..."))
        self.pushButton_Delete_file.setToolTip(_translate("MainWindow", "Delete file(s)"))
        self.label_Start.setText(_translate("MainWindow", "00:00:00"))
        self.label_End.setText(_translate("MainWindow", "00:00:00"))
        self.menuMain.setTitle(_translate("MainWindow", "Main"))
        self.menuAbout.setTitle(_translate("MainWindow", "About"))
        self.actionNew_Playllist.setText(_translate("MainWindow", "New Playlist"))
        self.actionFiles.setText(_translate("MainWindow", "Files"))
        self.actionFolder.setText(_translate("MainWindow", "Folder"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
        self.actionHelp.setText(_translate("MainWindow", "Help"))
        self.actionAbout.setText(_translate("MainWindow", "About"))
from widgets.equalizer import MyEqualizer
from widgets.tree_view import MyTreeView


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
